services:
  nginx:
    container_name: nginx_container
    image: nginx:latest
    restart: always
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    # IF YOU LEAVE THE IMAGE, DOCKERFILE IS SKIPPED
    # image: php:8-fpm
    container_name: php-fpm_container
    build:
      context: .
      dockerfile: ./Dockerfile.php-fpm
    image: fpm
    restart: always
    volumes:
      - .:/var/www/html